### ISSUE TITLE
Allow to pass custom context value properties to getInterpreter on createReactContextHelpers

### ISSUE THREAD

**Issue by otrebu** [VanTanev/xstate-helpers#2]
Hi there,

I am finding myself in a situation where I would like to add properties on the context value created with `createReactContextHelpers`.

In my case I am creating a form with `rc-field-form` and I would like to add it to the react context.
I tried to add it to the machine context, but when then trying to use it I am having issues. I think to do with the ability to pass refs around.

Aside from my quite specific scenario, do you think it would be good to be able to add other customer properties to the react context?

If the `getInterpreter` function was to returns something like: `{ interpreter, otherValues }`.

What do you think? Should I attempt a PR?

**Comment by VanTanev** [comment]
Can you share what the ideal API for your use case would look like?

**Comment by VanTanev** [comment]
@otrebu I think I'll close this. It's probably best to have a separate react context for data that is not a part of the machine.
