### ISSUE TITLE
@xstate/inspect is a peer dependency but not mentioned in the install docs.

### ISSUE THREAD

**Issue by samzmann** [VanTanev/xstate-helpers#3]
Hey! Thanks for this library!
I ran into the following issue after installing the library.

```
error: Error: Unable to resolve module `@xstate/inspect` from `node_modules/xstate-helpers/dist/xstate-helpers.cjs.production.min.js`: @xstate/inspect could not be found within the project.
```

This is easily fixed by installing `@xstate/inspect`.
I think it would be useful for the [Installation](https://github.com/VanTanev/xstate-helpers#installation) docs to mention that `@xstate/inspect` needs to be installed too.

PR coming.

**Comment by VanTanev** [comment]
Thank you for opening this.

I am currently unable to fix it, but will attempt to as soon as possible. The proper fix is two step - add peer dependency for xstate inspect and provide multiple entry points that allow you to load a specific helper without pulling in other deps.

**Comment by VanTanev** [comment]
Hey @LaVielle, I have released https://github.com/VanTanev/xstate-helpers/releases/tag/v1.0.0-beta.2

It addresses the issue by moving React helpers to a separate export. So, if you don't use @xstate/inspect, you won't get errors for it not existing.
